### ISSUE TITLE
OCX components show as unregistered after upgrade?

### ISSUE THREAD

**Issue by midwan** [luishdemetrio/Vb6VirtualRegistry#19]
Thanks for this project, I found it interesting and useful (yep, I happen to work at a company where we still have some VB6 apps around).

I've been trying to figure out a strange problem, and I was hoping you may have any ideas (or perhaps a solution even).

The first installation of a generated MSIX package works fine. But on an upgrade, the .OCX components contained are shown as "not registered", meaning the VB6 app starts up and complains about that (and does not work afterwards). Originally I thought I was messing something up in the upgrade or re-packaging, but it turns out, that's probably not the case: If I uninstall the app and just install the latest version instead, it works fine!

I've tested minimal upgrades, with only changing the version number in the AppxManifest.xml, and that also triggered the same problem. I've tried the process of packaging the MSIX from both Microsoft's MSIX Packaging Tool, the command line, and your VB6VirtualRegistry one. All of them resulted in the same behavior - works fine on a new installation, breaks on an upgrade. Works again if you uninstall and install the latest version.

So there seems to be something in the upgrade process itself, that breaks this. But I can't figure out what...

Have you run into this before?

**Comment by luishdemetrio** [comment]
Hi @midwan, thanks for your feedback! It was supposed to work.
For the updated version, are you using the following command to recreate the virtual registry?

Vb6VirtualRegistry.exe regsvr32 c:\unpackagedApp\VFS c:\unpackagedApp\registry.dat

What is weird is that it works after you uninstall the current version and you install the newest one.

Please let me know if you prefer having a call, so you can show me the issue, or if you prefer sharing the app so I can double check it.

**Comment by midwan** [comment]
Thanks for the reply!
I've also reported this to Microsoft (https://github.com/microsoft/msix-packaging/issues/517) but haven't received a response yet. To me it looks like something to do with the upgrade process of the MSIX mechanism, which manifests only on such a scenario for some reason.

I guess not many people are using .OCX components with VB6 these days, to run into this. 🤣 

My intention with this, was to be able to provide updated binaries, keeping every other dependency the same between them (components, registry, etc.), which means that an upgrade would normally only have one binary file changed, and nothing else. I don't recall if I re-run the `Vb6VirtualRegistry.exe regsvr32 c:\unpackagedApp\VFS c:\unpackagedApp\registry.dat` example you wrote above, but I did so many tests over the course of several days that it's possible I also tried that.

I know that MSIX does incremental byte-level upgrades, to maximize efficiency when downloading the newer package, and I can't help but wonder if that area is somehow related to the problem. I couldn't find a way to change that behavior, so I don't really know.

**Comment by luishdemetrio** [comment]
I will prepare a demo here later detailing the following steps:

1 - Package your application to MSIX (you can do it through MSIX Packaging Tool or manually as described [here](https://techcommunity.microsoft.com/t5/windows-dev-appconsult/how-msix-is-great-for-simplify-deployment-for-visual-basic-6-0/ba-p/3106904). 

2 - Unpack the application and replace the OCX. Follows a sample:

Vb6VirtualRegistry.exe unpack c:\MyApp\myapp.msix c:\MyApp\unpackagedFiles

3 - If you are just modifying or adding a single DLL or OCX, you don't need to recreate all the virtual registry, but you can modify it through the following command (don't forget the APPEND parameter):

Vb6VirtualRegistry.exe regsvr32 c:\MyApp\unpackagedFiles c:\MyApp\unpackagedFiles\registry.dat --append

In case you are not sure about what DLLs or OCXs were modified, you can recreate the entire virtual registry:

Vb6VirtualRegistry.exe regsvr32 c:\MyApp\unpackagedFiles\VFS c:\MyApp\unpackagedFiles\registry.dat

4 - Repack your app
Vb6VirtualRegistry.exe pack c:\MyApp\unpackagedFiles c:\MyApp\myapp.msix

5 - Sign your app:
 Vb6VirtualRegistry.exe sign c:\MyApp\myapp.msix c:\MyApp\mycertificate.pfx

The required step here, since you are modifying OCX/DLL, is that you have to add some CLSID to the registry.dat. That is the reason why you have to run again the Vb6VirtualRegistry.exe regsvr32 to update or recreate the registry.dat.

I will update later the [post](https://techcommunity.microsoft.com/t5/windows-dev-appconsult/how-msix-is-great-for-simplify-deployment-for-visual-basic-6-0/ba-p/3106904) with those details.

**Comment by midwan** [comment]
Thanks!
Just to clarify:
- I am _not_ updating any DLL/OCX files during upgrades. Those are just application requirements and they remain the same.
- The only thing that gets updated in newer packages, is the .EXE application binary, when there's a new version of it.
- Everything else remains the same, and is repackaged using an automated pipeline (which I wrote based on the manual steps, after testing that they produced the desired output).

In any case, it only seems to break if an existing version is installed, and we're doing an upgrade.
As I mentioned above, if I uninstall first and just install the latest version again, it works as expected.

**Comment by luishdemetrio** [comment]
Got it. It seems to be a bug. In case you can, please open a bug on the [Feedback Hub](https://www.microsoft.com/store/productId/9NBLGGH4R32N), add both Apps versions, and send me the ticket number. I can escalate the bug here.
